on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/fixxx' }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Responding to this comment: ${URL}"
      env:
        URL: ${{ github.event.comment.url }}
